default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: 'zeedog-github-api'
  username: 'aldowitzke'
  password: '123456789'
  host: localhost
  port: 5432

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: 'zeedog-github-api'
  username: 'aldowitzke'
  password: '123456789'

production:
  <<: *default
  database: zeedog-github-api
